import pygame as pg

pg.init()

SCREEN_INFO = pg.display.Info()
SCREEN_WIDTH = SCREEN_INFO.current_w
SCREEN_HEIGHT = SCREEN_INFO.current_h - 96

DISPLAY_WIDTH = 0.75 * SCREEN_WIDTH
DISPLAY_HEIGHT = SCREEN_HEIGHT

CONTROL_PANEL_WIDTH = SCREEN_WIDTH - DISPLAY_WIDTH
CONTROL_PANEL_HEIGHT = SCREEN_HEIGHT

SLIDER_WIDTH = 225
SLIDER_HEIGHT = 25

DESC_FONT = pg.font.SysFont(None, 24)
BUTTON_FONT = pg.font.SysFont(None, 64)

BLACK = pg.Color(0, 0, 0)
WHITE = pg.Color(255, 255, 255)
GRAY = pg.Color(100, 100, 100)
